# Generated by Django 4.2.2 on 2023-07-02 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('salary', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
